admin_master/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('admin_master_department',admin_master_department,name='master_department'),
    path('admin_master_designation',admin_master_designation,name='master_designation'),
    path('admin_master_qualification',admin_master_qualification,name='master_qualification'),
    path('admin_master_class',admin_master_class,name='master_class'),
    path('admin_master_division',admin_master_division,name='master_division'),
    path('admin_master_employee_category',admin_master_employee_category,name='master_employee'),
    path('edit_department/',datapick_edit,name="data"),
    path('update_depart/',update_dept_details,name="update_depart"),
    path('delete_depart/',del_depart,name='del_depart'),
    path('edit_designation/',datapick_desig_edit,name="datadesig"),
    path('update_desig/',update_desig_details),
    path('delete_desig/',del_desig,name='del_desig'),
    path('edit_qualification/',datapick_qualif_edit),
    path('update_qualification/',update_qualif_details),
    path('delete_qualif/',del_qualif),
    path('edit_class/',datapick_class_edit),
    path('update_class/',update_class_details),
    path('delete_class/',del_class),
    path('edit_division/',datapick_division_edit),
    path('update_division/',update_division_details),
    path('delete_division/',del_division),
    path('edit_emp/',datapick_edit_employee),
    path('update_emp/',update_emp_details),
    path('delete_emp/',del_emp),
    path('subject_page',subject,name="sub"),
    path('edit_sub/',datapick_edit_sub),
    path('update_sub/',update_sub_details), 
    path('del_sub/',del_sub)
]

ams/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('admin_general.urls')),
    path('',include('admin_master.urls')),
     path('',include('admin_employee.urls')),
]

admin_master/models.py
from django.db import models

# Create your models here.

class department_master(models.Model):
    name=models.CharField(max_length=100)
    code=models.CharField(max_length=30)
    status=models.IntegerField(default=1)

class designation_master(models.Model):
    name=models.CharField(max_length=100)
    code=models.CharField(max_length=30)
    status=models.IntegerField(default=1)

class qualification_master(models.Model):
    name=models.CharField(max_length=100)
    status=models.IntegerField(default=1)

class class_master(models.Model):
    name=models.CharField(max_length=100)
    status=models.IntegerField(default=1)

class division_master(models.Model):
    name=models.CharField(max_length=100)
    status=models.IntegerField(default=1)

class employee_category_master(models.Model):
    EMPLOYEE_CATEGORY_CHOICES=[
        (1,'Teacher'),
        (2,'Librarian'),
        (3,'cafeteria'),
        (4,'Accountant'),
        (5,'Others')
    ]
    name=models.CharField(max_length=100)
    area=models.IntegerField(choices=EMPLOYEE_CATEGORY_CHOICES)
    status=models.IntegerField(default=1)

class subjects(models.Model):
    sname=models.CharField(max_length=100)
    sstatus=models.BooleanField(default=1)

class subjectclass(models.Model):
    classid=models.ForeignKey("class_master",on_delete=models.CASCADE)
    subid=models.ForeignKey("subjects",on_delete=models.CASCADE)

admin_master/views.py
from django.shortcuts import render,redirect,get_object_or_404
from admin_master.models import *
from django.http import JsonResponse
from django.conf import settings
# Create your views here.

def admin_master_department(request):
    message=''
    msg=''
    if request.method=='POST':
        name=request.POST['dept_name'].strip()
        code=request.POST['dept_code'].strip()
        if not name or not code: 
               message="name and code are required"   
        elif department_master.objects.filter(name=name).exists():
               message="name already exists"
        elif department_master.objects.filter(code=code).exists():
               message="code already exists"
        else:
              ins=department_master(name=name,code=code)
              ins.save()
              msg="Successfully inserted"
    display=department_master.objects.all()
    return render(request,'admin_master_department_manage.html',{'msg':message,'mseg':msg,'display':display}) 

def datapick_edit(request):
       responsedata=department_master.objects.get(id=request.GET['id'])
       serialized_data={
              'name':responsedata.name,
              'code':responsedata.code,
              'status':responsedata.status,
       }
       return JsonResponse(serialized_data)

def update_dept_details(request):
  if request.method == 'GET':
    update_id = request.GET['updateId']
    update_name = request.GET['updateName'].strip()
    update_code = request.GET['updateCode'].strip()
    update_Status = request.GET['updateStatus']
    error_message=None
    success_message=None
    if not update_name or not update_code:
            error_message = 'Department name and code are required.'
    else:
        if department_master.objects.exclude(id=update_id).filter(name__iexact=update_name).exists():
            error_message = 'Department name already exists.'
        elif department_master.objects.exclude(id=update_id).filter(code__iexact=update_code).exists():
            error_message = 'Department code already exists.'
        else:
            obj= department_master.objects.get(id=update_id)
            obj.name = update_name
            obj.code = update_code
            obj.status=int(update_Status)
            obj.save()
            success_message = 'Department updated successfully.'
    response_data = {
    'errormessage': error_message,
    'successmessage': success_message,
    }
    return JsonResponse(response_data)
  
def del_depart(request):
      dept_id=request.GET['id']
      details=department_master.objects.get(id=dept_id) 
      details.delete()
      return JsonResponse('deleted!!!')    


def admin_master_designation(request):
    msg=''
    mesg=''
    if request.method=='POST':
            name=request.POST['desig_name'].strip()
            code=request.POST['desig_code'].strip()
            if not name or not code:
                msg="code and name are required"
            elif designation_master.objects.filter(name=name).exists():
               message="name already exists"
            elif designation_master.objects.filter(code=code).exists():
               message="code already exists"
            else:
                 ins=designation_master(name=name,code=code)
                 ins.save()
                 mesg="successfully inserted"
    display=designation_master.objects.all()
    return render(request,'admin_master_designation_manage.html',{'display':display,"msg":msg,'mesg':mesg})


def datapick_desig_edit(request):
       responsedata=designation_master.objects.get(id=request.GET['id'])
       serialized_data={
              'name':responsedata.name,
              'code':responsedata.code,
              'status':responsedata.status,
       }
       return JsonResponse(serialized_data)

def update_desig_details(request):
  if request.method == 'GET':
    update_id = request.GET['updateId']
    update_name = request.GET['updateName'].strip()
    update_code = request.GET['updateCode'].strip()
    update_Status = request.GET['updateStatus']
    error_message=None
    success_message=None
    if not update_name or not update_code:
            error_message = 'Designation name and code are required.'
    else:
        if designation_master.objects.exclude(id=update_id).filter(name__iexact=update_name).exists():
            error_message = 'Designation name already exists.'
        elif designation_master.objects.exclude(id=update_id).filter(code__iexact=update_code).exists():
            error_message = 'Code already exists.'
        else:
            obj= designation_master.objects.get(id=update_id)
            obj.name = update_name
            obj.code = update_code
            obj.status=int(update_Status)
            obj.save()
            success_message = 'Designation updated successfully.'
    response_data = {
    'errormessage': error_message,
    'successmessage': success_message,
    }
    return JsonResponse(response_data)
  
def del_desig(request):
      dept_id=request.GET['id']
      details=designation_master.objects.get(id=dept_id) 
      details.delete()
      return JsonResponse('deleted!!!')    

def admin_master_qualification(request):
    message=''
    msg=''
    if request.method=='POST':
        name=request.POST['qual_name'].strip()
        if not name: 
               message="name required"   
        elif qualification_master.objects.filter(name=name).exists():
               message="name already exists"
        else:
              ins=qualification_master(name=name)
              ins.save()
              msg="Successfully inserted"
    display=qualification_master.objects.all()
    return render(request,'admin_master_qualification_manage.html',{'msg':message,'mseg':msg,'display':display}) 

def datapick_qualif_edit(request):
       responsedata=qualification_master.objects.get(id=request.GET['id'])
       serialized_data={
              'name':responsedata.name,
              'status':responsedata.status,
       }
       return JsonResponse(serialized_data)

def update_qualif_details(request):
  if request.method == 'GET':
    update_id = request.GET['updateId']
    update_name = request.GET['updateName'].strip()
    update_Status = request.GET['updateStatus']
    error_message=None
    success_message=None
    if not update_name:
            error_message = 'Qualification name and code are required.'
    else:
        if qualification_master.objects.exclude(id=update_id).filter(name__iexact=update_name).exists():
            error_message = 'Qualification name already exists.'
        else:
            obj= qualification_master.objects.get(id=update_id)
            obj.name = update_name
            obj.status=int(update_Status)
            obj.save()
            success_message = 'Qualification updated successfully.'
    response_data = {
    'errormessage': error_message,
    'successmessage': success_message,
    }
    return JsonResponse(response_data)
  
def del_qualif(request):
      dept_id=request.GET['id']
      details=qualification_master.objects.get(id=dept_id) 
      details.delete()
      return JsonResponse('deleted!!!')    

def admin_master_class(request):
    message=''
    msg=''
    if request.method=='POST':
        name=request.POST['class_name'].strip()
        if not name: 
               message="name required"   
        elif class_master.objects.filter(name=name).exists():
               message="name already exists"
        else:
              ins=class_master(name=name)
              ins.save()
              msg="Successfully inserted"
    display=class_master.objects.all()
    return render(request,'admin_master_class_manage.html',{'msg':message,'mseg':msg,'display':display}) 

def datapick_class_edit(request):
       responsedata=class_master.objects.get(id=request.GET['id'])
       serialized_data={
              'name':responsedata.name,
              'status':responsedata.status,
       }
       return JsonResponse(serialized_data)

def update_class_details(request):
  if request.method == 'GET':
    update_id = request.GET['updateId']
    update_name = request.GET['updateName'].strip()
    update_Status = request.GET['updateStatus']
    error_message=None
    success_message=None
    if not update_name:
            error_message = 'class name required.'
    else:
        if class_master.objects.exclude(id=update_id).filter(name__iexact=update_name).exists():
            error_message = 'class name already exists.'
        else:
            obj= class_master.objects.get(id=update_id)
            obj.name = update_name
            obj.status=int(update_Status)
            obj.save()
            success_message = 'Class updated successfully.'
    response_data = {
    'errormessage': error_message,
    'successmessage': success_message,
    }
    return JsonResponse(response_data)
  
def del_class(request):
      dept_id=request.GET['id']
      details=class_master.objects.get(id=dept_id) 
      details.delete()
      return JsonResponse('deleted!!!') 


def admin_master_division(request):
    message=''
    msg=''
    if request.method=='POST':
        name=request.POST['division_name'].strip()
        if not name: 
               message="name required"   
        elif division_master.objects.filter(name=name).exists():
               message="division already exists"
        else:
              ins=division_master(name=name)
              ins.save()
              msg="Successfully inserted"
    display=division_master.objects.all()
    return render(request,'admin_master_division_manage.html',{'msg':message,'mseg':msg,'display':display}) 

def datapick_division_edit(request):
       responsedata=division_master.objects.get(id=request.GET['id'])
       serialized_data={
              'name':responsedata.name,
              'status':responsedata.status,
       }
       return JsonResponse(serialized_data)

def update_division_details(request):
  if request.method == 'GET':
    update_id = request.GET['updateId']

admin_master/templates/admin_master_class_manage.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<ul class="breadcrumb">
    <li><a href="#">Home</a></li>                    
    <li class="active">Class</li>
</ul>
<div class="page-title">                    
    <h2><span class="fa fa-arrow-circle-o-left"></span> Manage Class</h2>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
    <h3 class="panel-title">Add Class</h3>
<ul class="panel-controls">
<li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
</ul>
</div>

{% if mseg != '' %}
<button class="btn btn-success" onClick="noty({text: 'Successful action', layout: 'topRight', type: 'success'});">{{mseg}}</button>
{% endif %}

{% if msg != '' %}
<button class="btn btn-danger" onClick="noty({text: 'There was an error', layout: 'topRight', type: 'error'});">{{msg}}</button> 
{% endif %}

<form method="post">{% csrf_token %}
    <div class="panel-body">
        <div class="form-group">
    <div class="col-md-6 col-xs-6">                                                                                                                                                        
        <input type="text" class="form-control" name="class_name" autofocus placeholder="Class name"/>  
    </div>
    
    <div>
        <input type="hidden" value="{{ request.scheme }}://{{ request.get_host }}/edit_class/" id="link">
    </div>
</div>
</div>
    <div class="panel panel-default">
    <div class="panel-footer">
        <input type="reset" value="Clear form" class="btn btn-default" id="pc_refresh">                                   
        <button class="btn btn-primary pull-right">Submit</button>
    </div>
    </div>
</form>


     <!-- START DEFAULT DATATABLE -->
     <div class="panel panel-default">
        <div class="panel-heading">                                
            <h3 class="panel-title">List Class</h3>
            <ul class="panel-controls">
                <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                <li><a href="#" class="panel-refresh"><span class="fa fa-refresh"></span></a></li>
                <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
            </ul>                                
        </div>
        <div class="panel-body">
            <table class="table datatable">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Class Name</th>
                        <th>Status</th>
                        <th>Action</th>
                       
                    </tr>
                </thead>
                <tbody>
                    {% for i in display %}
                    <tr id="tr{{i.id}}">
                        <td>{{forloop.counter}}</td>
                        <td>{{i.name}}</td>
                        <td>{% if i.status == 1 %}<span class="label label-success">Active</span>{% else %}
                            <span class="label label-danger">Deactive</span>  {% endif %}</td>
                        <td><button class="btn btn-default btn-rounded btn-sm" onclick="edit_qual('{{i.id}}')"><span id="spinner{{i.id}}" class="fa fa-pencil"></span></button>
                            {% if i.status == 0 %}
                            <button class="btn btn-default btn-rounded btn-sm" onClick="delete_row('{{i.id}}','tr{{i.id}}')"><span class="fa fa-trash-o"></span></button>
                            {% endif %}
                            <input type="hidden" value="{{request.scheme}}://{{request.get_host}}/delete_class/" id="delink">
                        
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

    <!-- END DEFAULT DATATABLE -->
    <div class="modal" id="modal_basic" tabindex="-1" role="dialog" aria-labelledby="defModalHead" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="defModalHead">Edit Class</h4>
                </div>
            <div class="modal-body">
                    <div class="row">
                        <div class="panel-body">
                            <div class="form-group">
                    <div class="col-md-6 col-xs-6">                                                                                                                                                        
                        <input type="text" class="form-control" required id="edit_name" placeholder="Class name"/>  
                    </div>
                    <br><br><br>
        
                        <div class="col-md-12 col-xs-12">                                                                                            
                            <select  class="form-control" id="edit_status">
                                <option value="1">Active</option>
                                <option value="0">Deactive</option>    
                            </select>
                    </div>
                </div>
            </div>
        </div>      
        </div>
        
        <form>                       
            <div class="modal-footer">
                 <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                 <button class="btn btn-primary pull-right" onclick='update_qual()'>Update</button>
                 <input type="hidden" value="{{ request.scheme }}://{{ request.get_host }}/update_class/"  id="contacturl">
                 <input type="hidden" id="deptid">
            </div>
        </form>
            </div>             
        </div>
    </div>

            <div class="message-box animated fadeIn" data-sound="alert" id="mb-remove-row">
                <div class="mb-container">
                    <div class="mb-middle">
                        <div class="mb-title"><span class="fa fa-times"></span> Delete <strong>Data</strong> ?</div>
                        <div class="mb-content">
                            <p>Are you sure you want to Delete this row?</p>                    
                            <p>Press Yes if you sure.</p>
                        </div>
                        <div class="mb-footer">
                            <div class="pull-right">
                                <button class="btn btn-success btn-lg mb-control-yes">Yes</button>
                                <button class="btn btn-default btn-lg mb-control-close">No</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>  
        </div>
     </div>  

{% endblock %}

admin_master/templates/admin_master_employee_category_manage.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<ul class="breadcrumb">
    <li><a href="#">Home</a></li>                    
    <li class="active">Employee Category</li>
</ul>
<div class="page-title">                    
    <h2><span class="fa fa-arrow-circle-o-left"></span> Manage Employee Category</h2>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
    <h3 class="panel-title">Add Employee</h3>
<ul class="panel-controls">
<li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
</ul>
</div>

{% if mesg != '' %}
<button class="btn btn-success" onClick="noty({text: 'Successful action', layout: 'topRight', type: 'success'});">{{mesg}}</button>
{% endif %}

{% if msg != '' %}
<button class="btn btn-danger" onClick="noty({text: 'There was an error', layout: 'topRight', type: 'error'});">{{msg}}</button> 
{% endif %}

<form method="post">{% csrf_token %}
    <div class="col-md-6 col-xs-6">                                                                                                                                                        
        <input type="text" class="form-control" autofocus required name="emp_cat_name" placeholder="Employee Category name"/>  
    </div>
                <div class="form-group">
                    <div class="col-md-6 col-xs-6">                                                                                            
                        <select  class="form-control" name="area">
                            <option>--Area--</option>
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_ACCOUNTANT}}">Accountant</option>    
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_LIBRARY}}">Librarian</option> 
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_CAFETERIA}}">Cafeteria</option> 
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_TEACHER}}">Teacher</option> 
                            <option value="{{settings.EMPLOYEE_CATEGORY_AREA_OTHERS}}">Others</option> 
                        </select>
                </div>
            </div>
    
    <div class="panel panel-default">
    <div class="panel-footer">
        <button class="btn btn-default">Clear Form</button>                                    
        <button class="btn btn-primary pull-right">Submit</button>
    </div>
    </div>

</form>

     <!-- START DEFAULT DATATABLE -->
     <div class="panel panel-default">
        <div class="panel-heading">                                
            <h3 class="panel-title">List Employee categories</h3>
            <ul class="panel-controls">
                <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                <li><a href="#" class="panel-refresh"><span class="fa fa-refresh"></span></a></li>
                <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
            </ul>                                
        </div>
        <div class="panel-body">
            <table class="table datatable">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Employee category</th>
                        <th>Area</th>
                        <th>Status</th>
                        <th>Action</th>
                       
                    </tr>
                </thead>
                <tbody>
                    {% for i in display %}
                    <tr id="tr{{i.id}}">
                        <td>{{forloop.counter}}</td>
                        <td>{{i.name}}</td>
                        <td>{{i.get_area_display}}</td>
                        <td>{% if i.status == 1 %}<span class="label label-success">Active</span>{% else %}
                            <span class="label label-danger">Deactive</span>{% endif %}</td>
                        <td><button class="btn btn-default btn-rounded btn-sm" onclick="edit_emp('{{i.id}}')"><span id="spinner{{i.id}}" class="fa fa-pencil"></span></button>
                            {% if i.status == 0 %}
                            <button class="btn btn-default btn-rounded btn-sm" onClick="delete_row('{{i.id}}','tr{{i.id}}')"><span class="fa fa-trash-o"></span></button>
                            {% endif %}
                            <input type="hidden" value="{{request.scheme}}://{{request.get_host}}/delete_emp/" id="delink">
                            <input type="hidden" value="{{ request.scheme }}://{{ request.get_host }}/edit_emp/" id="link">
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

    <!-- END DEFAULT DATATABLE -->
    <div class="modal" id="modal_basic" tabindex="-1" role="dialog" aria-labelledby="defModalHead" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="defModalHead">Edit Employee Category</h4>
                </div>
            <div class="modal-body">
                    <div class="row">
                        <div class="panel-body">
                            <div class="form-group">
                    <div class="col-md-6 col-xs-6">                                                                                                                                                        
                        <input type="text" class="form-control" placeholder="Employee category name" id="edit_name" />  
                    </div>
                    
                        <div class="col-md-6 col-xs-6">                                                                                            
                            <select  class="form-control" id="edit_code">
                                <option selected="selected" disabled>--Area--</option>
                                <option value="{{settings.EMPLOYEE_CATEGORY_AREA_ACCOUNTANT}}">Accountant</option>    
                                <option value="{{settings.EMPLOYEE_CATEGORY_AREA_LIBRARY}}">Librarian</option> 
                                <option value="{{settings.EMPLOYEE_CATEGORY_AREA_CAFETERIA}}">Cafeteria</option> 
                                <option value="{{settings.EMPLOYEE_CATEGORY_AREA_TEACHER}}">Teacher</option> 
                                <option value="{{settings.EMPLOYEE_CATEGORY_AREA_OTHERS}}">Others</option> 
                            </select>
                    </div>
        
    
                    <br><br><br>
        
                        <div class="col-md-12 col-xs-12">                                                                                            
                            <select  class="form-control" id="edit_status">
                                <option value="1">Active</option>
                                <option value="0">Deactive</option>    
                            </select>
                    </div>
                </div>
            </div>
        </div>      
        </div>
        
        <form>                       
            <div class="modal-footer">
                 <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                 <button class="btn btn-primary pull-right" onclick='update_emp()'>Update</button>
                 <input type="text" value="{{ request.scheme }}://{{ request.get_host }}/update_emp/"  id="contacturl">
                 <input type="text" id="deptid">
            </div>
        </form>
            </div>             
        </div>
    </div>

            <div class="message-box animated fadeIn" data-sound="alert" id="mb-remove-row">
                <div class="mb-container">
                    <div class="mb-middle">
                        <div class="mb-title"><span class="fa fa-times"></span> Delete <strong>Data</strong> ?</div>
                        <div class="mb-content">
                            <p>Are you sure you want to Delete this row?</p>                    
                            <p>Press Yes if you sure.</p>
                        </div>
                        <div class="mb-footer">
                            <div class="pull-right">
                                <button class="btn btn-success btn-lg mb-control-yes">Yes</button>
                                <button class="btn btn-default btn-lg mb-control-close">No</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>  
        </div>
     </div>  

{% endblock %}